const data = {
  nyplLinks: [
    [
      { name: 'About NYPL',
        link: '/help/about-nypl',
      },
      { name: 'Press',
        link: '/help/about-nypl/media-center',
      },
      { name: 'Careers at NYPL',
        link: '/careers',
      },
      { name: 'Space Rental',
        link: '/spacerental',
      },
    ],
    [
      { name: 'Privacy Policy',
        link: '/help/about-nypl/legal-notices/privacy-policy',
      },
      { name: 'Other Policies',
        link: '/policies',
      },
      { name: 'Terms & Conditions',
        link: '/terms-conditions',
      },
      { name: 'Governance',
        link: '/help/about-nypl/leadership/board-trustees',
      },
    ],
    [
      { name: 'Rules & Regulations',
        link: '/help/about-nypl/legal-notices/rules-and-regulations',
      },
      { name: 'Accessibility',
        link: '/accessibility',
      },
      { name: 'Language',
        link: '/language',
      },
    ],
  ],
  socialMedia: [
    { name: 'NYPL on Facebook',
      link: 'https://www.facebook.com/nypl',
      id: 'nypl-icon-facebook',
      className: 'nypl-icon-facebook',
    },
    { name: 'NYPL on Twitter',
      link: 'https://twitter.com/nypl',
      id: 'nypl-icon-twitter',
      className: 'nypl-icon-twitter',
    },
    { name: 'NYPL on Instagram',
      link: 'https://instagram.com/nypl',
      id: 'nypl-icon-instagram',
      className: 'nypl-icon-instagram',
    },
    { name: 'NYPL on Tumblr',
      link: 'https://nypl.tumblr.com/',
      id: 'nypl-icon-tumblr',
      className: 'nypl-icon-tumblr',
    },
    { name: 'NYPL on Youtube',
      link: 'https://www.youtube.com/user/NewYorkPublicLibrary',
      id: 'nypl-icon-youtube',
      className: 'nypl-icon-youtube',
    },
  ],
};

export default data;
