const data = {
  column01: [
    { name: 'About NYPL',
      link: '/help/about-nypl',
    },
    { name: 'Press',
      link: '/help/about-nypl/media-center',
    },
    { name: 'Careers at NYPL',
      link: '/careers',
    },
    { name: 'Space Rental',
      link: '/spacerental',
    },
  ],
  column02: [
    { name: 'Privacy Policy',
      link: '/help/about-nypl/legal-notices/privacy-policy',
    },
    { name: 'Other Policies',
      link: '/policies',
    },
    { name: 'Terms & Conditions',
      link: '/terms-conditions',
    },
    { name: 'Governance',
      link: '/help/about-nypl/leadership/board-trustees',
    },
  ],
  column03: [
    { name: 'Rules & Regulations',
      link: '/help/about-nypl/legal-notices/rules-and-regulations',
    },
    { name: 'Accessibility',
      link: '/accessibility',
    },
    { name: 'Language',
      link: '/language',
    },
  ],
  socialMedia: [
    { name: 'Facebook',
      link: 'https://www.facebook.com/nypl',
      className: 'nypl-icon-facebook',
    },
    { name: 'Twitter',
      link: 'https://twitter.com/nypl',
      className: 'nypl-icon-twitter',
    },
    { name: 'Instagram',
      link: 'https://instagram.com/nypl',
      className: 'nypl-icon-instagram',
    },
    { name: 'Tumblr',
      link: 'https://nypl.tumblr.com/',
      className: 'nypl-icon-tumblr',
    },
    { name: 'Youtube',
      link: 'https://www.youtube.com/user/NewYorkPublicLibrary',
      className: 'nypl-icon-youtube',
    },
  ],
};

export default data;
